config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :articles, except: [:index]

  root   'articles#index'

  get    'signup', to: 'users#new'
  get    'about',  to: 'pages#about'
  get    'articles', to: 'articles#index'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 2, maximum: 105}
  validates :link, presence: true, format: { with: /(http|https):\/\/[a-zA-Z0-9\-\#\/\_]+[\.][a-zA-Z0-9\-\.\#\/\_]+/i }
  validates :user_id, presence: true
end

app/models/uri_validator.rb
class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    return if value.blank?
    begin
      uri = URI.parse(value)
      resp = uri.kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
      resp = false
    end
    unless resp == true
      record.errors[attribute] << (options[:message] || "is not an url")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 8, maximum: 60}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must log in first"
      redirect_to articles_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:index, :show]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was updated successfuly."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article has been destroyed."
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :link)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "login successful"
      redirect_to root_path
    else
      flash.now[:danger] = "Your email or password does not match"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "logout successful"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 100)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User update was successful."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User account has been created."
      redirect_to user_path(@user)
    else
      render 'users/new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User has been destroyed."
    redirect_to root_path
  end

    private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 40})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%= render "shared/errors", obj: @article %>
    <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1">
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control", placeholder: "title", autofocus: true %>
        </div>
        <div class="form-group">
          <%= f.text_field :link, class: "form-control", placeholder: "https://", autofocus: true %>
        </div>
        <div class="form-group">
          <div class="col-xs-12">
            <h3><%= f.submit(@article.new_record? ? "create" : "update", class: "btn btn-primary btn-lg") %> [ <%= link_to "Cancel", root_path %> ]</h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>New Article <%= link_to new_article_path do %><i class="glyphicon glyphicon-plus"></i></h1>
<% end %>

<div class="container">
  <% @articles.each do |article| %>
    <div class="well col-xs-12 col-md-8">
      <div class="col-xs-3 col-md-1 grav-top-pad">
        <%= link_to gravatar_for(article.user), user_path(article.user) %>
        <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
          <%= link_to edit_article_path(article) do %><i class="glyphicon glyphicon-edit icon-pad"></i>
          <% end %>
          <%= link_to article_path(article), method: :delete,
                data: {confirm: "Are you sure you want to delete this article?"} do %>
                <i class="glyphicon glyphicon-trash icon-pad"></i>
          <% end %>
        <% end %>
      </div>
  <div class="container">
    <div class="row">
    <div class="col-xs-9 col-md-11">
      <h4><%= link_to article.title, article_path(article) %></h4>
      <p><%= article.link %></p>
    </div>
  </div>
  <% end %>
</div>

  <div align="center"><%= will_paginate %></div>

app/views/articles/new.html.erb
<div align="center">
  <h1>Add an article</h1>
  <p>Add a link to a usefull article or resource</p>

<%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10">
      <div class="col-xs-1 grav-top-pad">
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
      </div>
      <div class="col-xs-11">
        <h2><%= @article.title %></h2>
      </div>
    </div>
  </div>
<div class="container">
  <div class="col-xs-10">
    <% if @article.user %>

    <h4><%= link_to @article.title, "#{@article.link}", target: "_blank" %></h4>

    <% end %>
  </div>
</ul

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#"><%= link_to "Read my code", root_path, id: "logo" %></a>
        <ul class="nav navbar-nav">
        <li><%= link_to new_article_path do %>
          <i class="glyphicon glyphicon-plus">article</i>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "users", users_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "my reading list", root_path %></li>
            <li><%= link_to "my profile", root_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "logout", logout_path, method: :delete  %></li>
          </ul>
          <% else %>
            <li><%= link_to "signup", signup_path %></li>
            <li><%= link_to "login", login_path %></li>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadMyCode</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="pannel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><br />
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control", placeholder: "email", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "password", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-xs-12">
      <h3><%= f.submit(@user.new_record? ? "sign up" : "update", class: "btn btn-primary btn-lg") %> [ <%= link_to "Cancel", root_path %> ]</h3>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">edit user</h1>

<%= render 'users/form' %>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>
  <h3><%= link_to user.email, user_path(user) %></h3>
  <% if logged_in? && (current_user == user || current_user.admin? ) %>
    <%= link_to "edit", edit_user_path(user), class: "btn btn-xs btn-success" %>
    <%= link_to "delete", user_path(user), method: :delete,
        data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  <% end %>
<% end %>
<div align="center">
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1">
    <h1>Sign up</h1>
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/show.html.erb
<h1>user show</h1>